### ISSUE TITLE
certain parts fail to annotate.

### ISSUE THREAD

**Issue by picousse** [Edinburgh-Genome-Foundry/Geneblocks#2]
Hi,
For most of my stuff this package is doing a great job. However for certain parts, it fails. And I don't understand why.
I've tried to make a reprex:

```python3
import geneblocks
from pprint import pprint
part = geneblocks.load_record('bcd.gb', name = 'insert')
plas = geneblocks.load_record('empty_plasmid_reprex.gb', name = 'plasmid')
blocks = geneblocks.CommonBlocks.from_sequences([part, plas],   min_block_size = 10)
new_records = blocks.copy_features_between_common_blocks(inplace=True)
annotated_plasmid = new_records['plasmid']
print(annotated_plasmid.features)
```
bcd.gb
```genbank
LOCUS       insert                    71 bp    DNA              UNK 01-JAN-1980
DEFINITION  BCD0014_GalE_BCD18.
ACCESSION   insert
VERSION     insert
KEYWORDS    .
SOURCE      .
  ORGANISM  .
            .
FEATURES             Location/Qualifiers
     misc_feature    1..71
                     /label="BCD0014_GalE_BCD18"
ORIGIN
        1 ataagcctaa aggagggaat tatgagagtt ctggttaaac atcttaatca tgcgacggag
       61 cgtttctaat g
//
```

empty_plasmid_reprex.gb
```genbank
LOCUS       Exported                2708 bp ds-DNA     circular SYN 25-MAY-2020
DEFINITION  description?.
ACCESSION   .
VERSION     .
KEYWORDS    .
SOURCE      synthetic DNA construct
  ORGANISM  synthetic DNA construct
REFERENCE   1  (bases 1 to 2708)
  AUTHORS   .
  TITLE     Direct Submission
  JOURNAL   Exported Monday, May 25, 2020 from SnapGene 5.1.3
            https://www.snapgene.com
FEATURES             Location/Qualifiers
     source          1..2708
                     /organism="synthetic DNA construct"
                     /mol_type="other DNA"
ORIGIN
        1 agataacgac gatactgaag gaagtttacg gtgcgttaca accttacaat aataggactg
       61 ggatacttct actgatagtt ttctgtggac ccgttgatgt aaataataat tttttcatgt
      121 tgaaaatctc caaaaaaaaa ggctccaaaa ggagccttta attgtatcgg tttatcagct
      181 tgctttcagc ctatttgttt gacagaattt cggcaagtgc ccgcgctgga atgatggcaa
      241 tgttcgtcat tagaaacgct ccgtcgcatg attaagatgt ttaaccagaa ctctcataat
      301 tccctccttt aggcttatac tcatccacac attatacgag ccggatgatt aattgtcgaa
      361 gggagtcaat aggagaagtt tccaaccttt tatcgcaggc aatcgtatct accagtgaat
      421 cttagggttt ctccgtgtaa ataaactacg actggcacag attgaatact ttcgccgctg
      481 ataactttgt atgtctgctc ctcggagttc gttaaggctt gatctctaca gcttattaag
      541 cccagaacag aacatctttt tcacaacggt cattagaaac cctccgcagc atgattaaga
      601 tgtttaacca gaactctcat aattccctcc tttaggctta tactctccac ataaattacg
      661 agccggatga ttaattgtca aagggtaact cagacctcaa cggattgtca gtgtgataga
      721 cttattggca cgagatactt ttcaaattgt gaaagccctc tcagcgatag aatacggttg
      781 gataatagtc cgaaggttta caataagtta ttgagagacc ataggggtga tcttccgtca
      841 caggtaggcg cccgcggtgc gggtgccagg gcgtgccccc gggctccccg ggcgcgtact
      901 ccacctgtca gaccaagttt actcatataa ttgcggatgt tgcgattact tcgccaacta
      961 ttgcgataac aagaaaaagc cagcctttca tgatatatct cccaatttgt gtagggctta
     1021 ttatgcacgc ttaaaaataa taaaagcaga cttgacctga tagtttggct gtgagcaatt
     1081 atgtgcttag tgcatctaac gcttgagtta agccgcgccg cgaagcggcg tcggcttgaa
     1141 cgaattgtta gacattattt gccgactacc ttctctgata gttgagtcga tacttcggcg
     1201 atcaccgctt ccctcatgat gtttaacttt gttttagggc gactgccctg ctgcgtaaca
     1261 tcgttgctgc tccataacat caaacatcga cccacggcgt aacgcgcttg ctgcttggat
     1321 gcccgaggca tagactgtac cccaaaaaaa cagtcataac aagccatgaa aaccgccact
     1381 gcgccgttac caccgctgcg ttcggtcaag gttctggacc agttgcgtga gcgcatacgc
     1441 tacttgcatt acagcttacg aaccgaacag gcttatgtcc actgggttcg tgccttcatc
     1501 cgtttccacg gtgtgcgtca cccggcaacc ttgggcagca gcgaagtcga ggcatttctg
     1561 tcctggctgg cgaacgagcg caaggtttcc agcgtaagac gggtaagcct gttgatgata
     1621 ccgctgcctt actgggtgca ttagccagtc tgaatgacct gtcacgggat aatccgaagt
     1681 ggtcagactg gaaaatcaga gggcaggaac tgctgaacag caaaaagtca gatagcacca
     1741 catagcagac ccgccataaa acgccctgag aagcccgtga cgggcttttc ttgtattatg
     1801 ggtagtttcc ttgcatgaat ccataaaagg cgcctgtagt gccatttacc cccattcact
     1861 gccagagccg tgagcgcagc gaactgaatg tcacgaaaaa gacagcgact caggtgcctg
     1921 atggtcggag acaaaaggaa tattcagcga tttgcccgag cttgcgaggg tgctacttaa
     1981 gcctttaggg ttttaaggtc tgttttgtag aggagcaaac agcgtttgcg acatcctttt
     2041 gtaatactgc ggaactgact aaagtagtga gttatacaca gggctgggat ctattctttt
     2101 tatttacaag ttttccagca aaggtctagc agaatttaca gatacccaca actcaaagga
     2161 aaaggactag taattatcat tgactagccc atctcaattg gtatagtgat taaaatcacc
     2221 tagaccaatt gagatgtatg tctgaattag ttgttttcaa agcaaatgaa ctagcgatta
     2281 ttttccagaa accacactag agaacatact ggctaaatac ggaaggatct gaggttctta
     2341 tggctcttgt atctatcagt gaagcatcaa gactaacaaa caaaagtaga acaactgttc
     2401 accgttacat atcaaaggga aaactgtcca tatgcacaga tgaaaacggt gtaaaaaaga
     2461 tagatacatc agagctttta cgagtttttg gtgcattcaa agctgttcac catgaacaga
     2521 tcgacaatgt aacgccaacc aacaacccga ttcgtggaca ggagtcagga tcgattgtgt
     2581 aggctggagc tgcttcccgc ggtgcgcact ttaaatggcg cgccttacgt cggggtctca
     2641 aggggaaaac ttatctacgg tcttacaatc cacttcttcg tgagtatcaa ctgtgctggg
     2701 aaaaactc
//
```

All tips and hints are welcome!

**Comment by picousse** [comment]
I think it has to do with the fact that certain parts appear multiple times.

The common blocks are being found. However it fails (I think) in the ```copy_features_between_common_blocks```function, more specifically n the itertools combination.

But then I'm a bit lost... Not sure how to fix this...

**Comment by Zulko** [comment]
Sorry for that! Do you have a minimal example to reproduce the issue?

**Comment by picousse** [comment]
I think the above code (post 1) can be used in the as a minimal example?
At least for me that doesn't seem to annotate properly.

I want to help, but no idea how. I'm a bit lost in the itertools.combination loop.

Maybe the bigger picture: I have a library of parts, and poorly annotated plasmids. I want to annotate the plasmids with the parts in the that library.

And that is were your code comes in (which does seem to work fine for most of the parts). For some of them it doesn't, and I think it might have to do something with parts being found multiple times.

It would already be great feedback if you could repeat the issue.

Thx

**Comment by Zulko** [comment]
Sorry I read too fast. @veghp any idea what it could be? I have no time now but might get some over the weekend (hoping this is a straightforward fix).

**Comment by picousse** [comment]
No probs. All help is welcome.
I'll try to decypher the code as well this weekend, and see if I can help in some kind of way...

**Comment by veghp** [comment]
Thanks for bringing attention to this. I can reproduce the error using your files. Also if `min_block_size = 70`, so that there is only one match, the annotation is correct:

```
import dna_features_viewer
graphic_record = dna_features_viewer.BiopythonTranslator().translate_record(annotated_plasmid)
ax, _ = graphic_record.plot(figure_width=5)
```
![index](https://user-images.githubusercontent.com/31794642/83639801-1e033380-a5a3-11ea-87ec-01bde9a7f215.png)

So the problem is indeed having multiple matching blocks as you suggested. I'll look into this.

**Comment by picousse** [comment]
In fact isn't that weird? that it does a good job when setting the block size higher? This would mean it looks for common blocks with or without features (or maybe that was the point?)

**Comment by veghp** [comment]
The **problem** is that the blocks are recognised, but there is no corresponding feature in the original sequence (insert); i.e. there is an implicit assumption that only annotated features will be recognised as blocks (and not sections of features).

Probably the best **solution (i)** is to _use only the annotated features in the insert (part) as potential blocks._ 

Another solution **(ii)** is to generate combinations of adjacent blocks until they make up a feature, then transfer. 

In the meantime, a workaround could be visualizing the part annotated with blocks to see how to set `min_block_size`:

```
min_block_size = 10

import geneblocks
import dna_features_viewer
from pprint import pprint

part = geneblocks.load_record('bcd.gb', name = 'insert')
plas = geneblocks.load_record('empty_plasmid_reprex.gb', name = 'plasmid')
blocks = geneblocks.CommonBlocks.from_sequences([part, plas], min_block_size = min_block_size)
# Here we make an annotated part (insert) sequence:
sequences_with_annotated_blocks = blocks.sequences_with_annotated_blocks()
graphic_record = dna_features_viewer.BiopythonTranslator().translate_record(sequences_with_annotated_blocks['insert'])
ax, _ = graphic_record.plot(figure_width=5)
```
![index](https://user-images.githubusercontent.com/31794642/83764089-67ba4f80-a671-11ea-8e74-260c07b6c5d1.png)

So in this case, the block size needs to be increased.

**Comment by picousse** [comment]
Hi,
Does that mean you get annotation of the original part?
If I do string searching, I do find the original block in the plasmid. However it doesn't do that using that code, for me at least.

Could you confirm whether you get or don't get the part annotated in the final construct? It might still be a problem at my end.

Thanks for the help.

I think the assumption of only transferring complete features is indeed a correct one. I wouldn't change that.

**Comment by veghp** [comment]
Just updated my answer. There are multiple blocks making up the feature, so the block size needs to be increased. It probably should be set to the length of the smallest part feature you want to transfer:
if `min_block_size = 70`, you get:
![index3](https://user-images.githubusercontent.com/31794642/83768069-40b24c80-a676-11ea-920c-a5fd0d579e23.png)

```
new_records = blocks.copy_features_between_common_blocks(inplace=True)
annotated_plasmid = new_records['plasmid']

graphic_record = dna_features_viewer.BiopythonTranslator().translate_record(annotated_plasmid)
ax, _ = graphic_record.plot(figure_width=5)
```
![index4](https://user-images.githubusercontent.com/31794642/83768136-53c51c80-a676-11ea-8d02-7e5e73d9017a.png)

**Comment by Zulko** [comment]
Hi there, the "transfer features" was a nice feature to add on top of Geneblock's "find common blocks" feature, but now I am wondering if it's not overkill for @picousse 's use case.

A simpler approach (which may be slower on many sequences as it doesn't use BLAST) would be:
- Go once through all your records and compile every feature into a dictionnary [sequence -> feature] (and maybe also [rev_sequence -> rev_feature] for reverse-complemented features).
- Go a second time through your sequences and for every match from the sequences dict, add a feature (if the feature isn't already there).

**Comment by picousse** [comment]
Owkay, and because if finds more sub parts of the original feature multiple times, it finds those (and thus no longer the complete feature).

@Zulko. You might be right. I however I always have struggled with features overlapping the genbank start. And therefore I thought you're code could come in handy.

Thanks a lot for the help, guys!

Congratulations btw, on the awesome software (this, and the other modules). Truly impressed.
