### ISSUE TITLE
common blocks positions in alignment

### ISSUE THREAD

**Issue by ffa** [Edinburgh-Genome-Foundry/Geneblocks#4]
How may I retrieve a common block's position from the alignment done by blast?
The positions given by CommonBlocks seems to be the positions of a common block in each of sequences it appears in before the alignment. I am looking for the position of a common block in the alignment.
Please guide me.

**Comment by Zulko** [comment]
Hmmm I am not completely sure what you mean to be honnest, which alignment are you refering to? The alignment of each pair of sequences?

**Comment by ffa** [comment]
Yes, I want the positions from the alignment for the common blocks. Is there another alignment done in addition to the ones blast does?
