### ISSUE TITLE
Error while following example: 'numpy.ndarray' object has no attribute 'figure' 

### ISSUE THREAD

**Issue by naturepoker** [Edinburgh-Genome-Foundry/Geneblocks#6]
Hi, 

I'm trying to follow through the two-sample comparison/difference example on the github page, and am getting a numpy.ndarray related error. 

The error message is:

`Traceback (most recent call last):
  File "gbk_comparison_plot.py", line 11, in <module>
    common_blocks.plot_common_blocks(axes=axes[:-1])
  File "/home/.local/lib/python3.9/site-packages/geneblocks/CommonBlocks/CommonBlocks.py", line 218, in plot_common_blocks
    fig = axes[0].figure
AttributeError: 'numpy.ndarray' object has no attribute 'figure'
`

The code I'm using is:

from geneblocks import DiffBlocks, CommonBlocks, load_record
import matplotlib.pyplot as plt

seq_1 = load_record("gene_3.gbk")
seq_2 = load_record("gene_6.gbk")

common_blocks = CommonBlocks.from_sequences({'seq1': seq_1, 'seq2': seq_2})
diff_blocks = DiffBlocks.from_sequences(seq_1, seq_2).merged()

fig, axes = plt.subplots(6, 2, figsize=(30, 16))
common_blocks.plot_common_blocks(axes=axes[:-1])
diff_blocks.plot(ax=axes[-1], separate_axes=False)
axes[-1].set_xlabel("Gene 3 and 6 difference")
fig.savefig("3_6_comparison.png", bbox_inches='tight')

What could I be doing wrong? Any help appreciated. 

Thank you!

**Comment by veghp** [comment]
Thanks for bringing attention to this, I agree this was a tricky one.

Unfortunately matplotlib's `plt.subplots` seems to return different object types, depending on input. If you have a 1-dimensional grid:
```python
fig, axes = plt.subplots(3, 1)
type(axes)
# numpy.ndarray
type(axes[0])
# matplotlib.axes._subplots.AxesSubplot
```
For 2-dimensional grids:
```python
fig, axes = plt.subplots(3, 3)
type(axes)
# numpy.ndarray
type(axes[0])
# numpy.ndarray
type(axes[0][0])
# matplotlib.axes._subplots.AxesSubplot
```

Try this in your code:
```python
from geneblocks import DiffBlocks, CommonBlocks, load_record
import matplotlib.pyplot as plt

seq_1 = load_record("gene_3.gbk")
seq_2 = load_record("gene_6.gbk")

common_blocks = CommonBlocks.from_sequences({'seq1': seq_1, 'seq2': seq_2})
diff_blocks = DiffBlocks.from_sequences(seq_1, seq_2).merged()

fig, axes = plt.subplots(2, 3, figsize=(8, 8))
diff_blocks.plot(ax=axes[1][0], separate_axes=False)   # <---

common_blocks.plot_common_blocks(axes=axes[0])   # <---

axes[1][0].set_xlabel("Gene 3 and 6 difference")   # <---
fig.savefig("3_6_comparison.png", bbox_inches='tight')
```
![3_6_comparison](https://user-images.githubusercontent.com/31794642/152995295-b877ad27-a6a8-4ede-a63d-8c41eabff0a9.png)

**Comment by naturepoker** [comment]
Fixing the code as you suggested (and changed the subplot to 2,2) and now the plots are generating without huge issues - the layout is a little interesting, but I get a feeling a little gimp cut and paste here might be faster than finding a python solution for myself :) 

I do have one more side question of sorts, what does the colored 'block_#s' on the plots denote? I'm guessing it's the regions with detected changes, but do the colors correspond to something? 

Thank you for the help!

**Comment by veghp** [comment]
GeneBlocks finds common, identical, blocks in a group of DNA sequences, and these blocks are numbered. Each number has a different colour to help reading the plot.

**Comment by naturepoker** [comment]
Well noted, I think this issue can be closed now. 

Again, thank you so much for walking me through the problem! This is a brilliant tool.
