### ISSUE TITLE
Gene Blocks does not support protein sequences

### ISSUE THREAD

**Issue by wenyuhaokikika** [Edinburgh-Genome-Foundry/Geneblocks#8]
it show two protein difference，but no block
![protein](https://github.com/Edinburgh-Genome-Foundry/Geneblocks/assets/40107519/b2cb8a36-b0c5-4cdc-b440-60caaf264be7)

I think it may be show block and difference(-102nuc, -102pip) like DNA sequence

![DNA](https://github.com/Edinburgh-Genome-Foundry/Geneblocks/assets/40107519/3874ac53-4354-48ac-8bda-9aadf63e6944)

**Comment by veghp** [comment]
Thanks, yes protein (amino acid) sequences were not its intended use-case as far as I know, so it's a nice bonus we have that it still can annotate differences between 2 amino acid sequences.

A workaround could be to reverse-translate the protein sequences, using the same codon for each amino acid, then compare the sequences.

Ultimately this is probably outside the scope of this package, but it's an interesting use case. I made a note for potentially adding this as a feature, but probably there are better tools to compare multiple protein sequences, that also can take into consideration amino acid similarities or transition probabilities etc.

**Comment by wenyuhaokikika** [comment]
Thank you, I found another tools to draw mutations  for protein[Plot protein](https://sites.google.com/site/plotprotein/home)
